### ISSUE TITLE
Request support for the general hubitat notification driver rather than just pushover

### ISSUE THREAD

**Issue by yougotborked** [CobraVmax/Hubitat#1]
It would be awesome if any time you sent a notification, you were able to use any driver that registers themselves as a notification driver. I think specifically to be able to use the 
```
capability "Notification"
```

Some custom ones include the ifttt driver https://community.hubitat.com/t/ifttt-notifications-driver/3895
or the Twilio one linked in the same thread. I'm also working on writing my own slack webhook driver similar to those two. I think that would also unlock your apps using sms.

**Comment by mbaran5** [comment]
I'd like to also vote for this enhancement. Now that there's a native app with notifications, this would let us send free push notifications rather than using pushover.
